//! Agent internal state types.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A single reasoning step in the agent's thought chain
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningStep {
    /// Iteration number (1-based)
    pub iteration: u32,

    /// The thinking content generated by LLM
    pub thinking: String,

    /// Timestamp when this step was recorded
    pub timestamp: DateTime<Utc>,

    /// Duration of LLM call in milliseconds (if available)
    pub duration_ms: Option<u64>,
}

impl ReasoningStep {
    pub fn new(iteration: u32, thinking: String, duration_ms: Option<u64>) -> Self {
        Self {
            iteration,
            thinking,
            timestamp: Utc::now(),
            duration_ms,
        }
    }
}

/// Record of a single tool call during agent execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallRecord {
    pub tool_name: String,
    pub arguments: String,
    pub result: String,
    pub iteration: u32,
    pub success: bool,
}
