apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: agent-server
    app.kubernetes.io/part-of: vol-agent
spec:
  project: default
  source:
    repoURL: git@github.com:BestNathan/vol.git
    targetRevision: main
    path: deploy/argocd/manifests/agent-server
    directory:
      recurse: true
      exclude: secret.example.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vol-agent-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
