apiVersion: apps/v1
kind: Deployment
metadata:
  name: vol-monitor
  namespace: deribit
  labels:
    app: vol-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vol-monitor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vol-monitor
    spec:
      restartPolicy: Always
      containers:
      - name: vol-monitor
        image: crpi-ck06yio90i1ttwlz.cn-beijing.personal.cr.aliyuncs.com/n_common/vol-monitor:latest
        imagePullPolicy: Always
        args:
          - "--config"
          - "/etc/vol-monitor/config.toml"
        volumeMounts:
        - name: config
          mountPath: /etc/vol-monitor
          readOnly: true
        env:
        - name: RUST_LOG
          value: "info"
      volumes:
      - name: config
        configMap:
          name: vol-monitor-config
          items:
          - key: config.toml
            path: config.toml
