---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-bestnathan
  namespace: vol-agent-system
spec:
  encryptedData:
    .dockerconfigjson: AgADBDQLC70wkwTKdeth1lkkfIZT21WPQkNZDcsAibz/7aqtjQvMPwBVu4Tc7g0JVcMy1TD3EDUbYtqOv8hgPXdmTkf0QxKiuv4tJ7sGtPP21iyqIs5d9+I3rNZc11I+x4q6P2RUhccSO1GjNdi8y75n2MuBU3coBiFDIn+zEX28H/2inrdERa3esMPLKxW4V5e/obel8gXjLYGRsJ7kVXq7Sgl/pBPctFZOFcsQJhUTz/KmsENJeJfUOOwbEo8UwK5OUye7VjzZueH1bRPCq8urclvUcLiZ69xY4pYTkuTrxjMbVhgJgmTE2FI+//u9aYpzBpcGIDUYUzsIGO+ptQAt7hDLr3h4Nq8CXUyiE+RjbR0BuMrSwle3pIx1tPsH3S007ksJm9ihvQEdu6EAGWM1KohOttCVXvrfpyguXYHtHrUaMLuzvdPY7pEzXC53WaIpE3BTA2bDaWFaYuIkn8Z+gfvwu6P89Qx0CbVK0MAxNqjOOA/IGMcL5JQe9YOUZC9kdFjHU/tZPzlOABQ5Ml+lfoWU/YvrI6K4OOca8xNejywNotKIDzaMn56jDWCDfFi1swbA1ouFev7h1kisNxpms5giFCSTXKnNJ5rPaSeqQqC7m0QMm6iTkVPfTtzIWp/q5duRemwlo+CmcL/hH6x+pYTFpuAqQPNmt5Zw6dKS1+EucfDeNcvZ5/nIGKVNHlZ57ZTJ5t3Emh9gfMdSmQ2AyG+LpC/mjNng31aWNFm31aBE4ROEdHg4GJU5RJDQL8+TQdysOTiwPpv8kVX8+8HMRrXVVgVuaKrHPS4mQ0qZxmR2x+yt9GPpHg8mLgCUVkMBc3DLq6bzR/FVcDtYBwamCjw7W4hsPzoUeqvYRddhoJ0QJYGQ+xqRdjw4wFdlo0Un2EigX/JXE7bbL1LatA5hIOUxnCPkEG9ML6AgB4N1u/4J6Q==
  template:
    metadata:
      name: ghcr-bestnathan
      namespace: vol-agent-system
    type: kubernetes.io/dockerconfigjson
