use crate::models::{OptionType, Tenor, VolatilityData};
use serde::{Deserialize, Serialize};

/// Alert types supported by the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AlertType {
    AbsoluteIv { threshold: f64 },
    RateChange { window_hours: u32, change_pct: f64 },
    TermStructure { spread_pct: f64 },
    Skew { skew_pct: f64 },

    /// Portfolio margin ratio alert
    #[serde(rename = "portfolio_margin")]
    PortfolioMargin { current: f64, threshold: f64 },
    /// Portfolio free balance alert
    #[serde(rename = "portfolio_balance")]
    PortfolioBalance { current: f64, threshold: f64 },
    /// Portfolio delta exposure alert
    #[serde(rename = "portfolio_delta")]
    PortfolioDelta { current: f64 },
    /// Portfolio PnL alert
    #[serde(rename = "portfolio_pnl")]
    PortfolioPnL { current: f64, threshold: f64 },
    /// Portfolio Greeks alert
    #[serde(rename = "portfolio_greek")]
    PortfolioGreek { greek: String, current: f64, threshold: f64 },
}

impl std::fmt::Display for AlertType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AlertType::AbsoluteIv { .. } => write!(f, "absolute_iv"),
            AlertType::RateChange { .. } => write!(f, "rate_change"),
            AlertType::TermStructure { .. } => write!(f, "term_structure"),
            AlertType::Skew { .. } => write!(f, "skew"),
            AlertType::PortfolioMargin { .. } => write!(f, "portfolio_margin"),
            AlertType::PortfolioBalance { .. } => write!(f, "portfolio_balance"),
            AlertType::PortfolioDelta { .. } => write!(f, "portfolio_delta"),
            AlertType::PortfolioPnL { .. } => write!(f, "portfolio_pnl"),
            AlertType::PortfolioGreek { greek, .. } => write!(f, "portfolio_greek_{}", greek),
        }
    }
}

/// An alert generated by an AlertHandler
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Alert type
    pub alert_type: AlertType,

    /// Tenor classification (short/medium/long)
    pub tenor: Tenor,

    /// Symbol that triggered the alert
    pub symbol: String,

    /// Current IV value
    pub iv: f64,

    /// Message to send to user
    pub message: String,

    /// Unix timestamp in milliseconds
    pub timestamp: u64,

    /// Data source name
    pub source: String,

    /// Current index price of the underlying asset
    pub index_price: f64,

    /// Days to expiration
    pub dte: u32,

    /// Option type (call/put)
    pub option_type: OptionType,

    /// Moneyness ratio (spot / strike)
    pub moneyness: f64,

    /// Option mark price in coin units (e.g., 0.05 BTC or 0.5 ETH)
    pub mark_price_coin: f64,
}

impl Alert {
    /// Get option mark price in USD
    pub fn mark_price_usd(&self) -> f64 {
        self.mark_price_coin * self.index_price
    }

    pub fn new(
        alert_type: AlertType,
        tenor: Tenor,
        symbol: String,
        iv: f64,
        message: String,
        timestamp: u64,
        source: String,
        index_price: f64,
        dte: u32,
        option_type: OptionType,
        moneyness: f64,
        mark_price_coin: f64,
    ) -> Self {
        Self {
            alert_type,
            tenor,
            symbol,
            iv,
            message,
            timestamp,
            source,
            index_price,
            dte,
            option_type,
            moneyness,
            mark_price_coin,
        }
    }
}

/// Action to take after an alert fires
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AlertAction {
    /// Send the alert and continue monitoring
    Send,
    /// Suppress this alert (e.g., due to cooldown)
    Suppress,
    /// Stop monitoring this condition
    Stop,
}

/// AlertHandler trait - evaluates volatility data and emits alerts.
///
/// All alert handler plugins (absolute_iv, rate_change, etc.) must implement this trait.
#[async_trait::async_trait]
pub trait AlertHandler: Send + Sync {
    /// Returns the name of this alert handler (e.g., "absolute_iv", "rate_change")
    fn name(&self) -> &str;

    /// Evaluate incoming data and optionally return an Alert.
    /// Returns None if no alert should be fired.
    fn evaluate(&self, data: &VolatilityData) -> Option<Alert>;

    /// Called when an alert fires. Returns the action to take.
    #[allow(async_fn_in_trait)]
    async fn on_alert(&self, alert: &Alert) -> crate::error::Result<AlertAction>;
}
