use crate::models::Tenor;
use serde::{Deserialize, Serialize};

/// Alert types supported by the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AlertType {
    AbsoluteIv { threshold: f64 },
    RateChange { window_hours: u32, change_pct: f64 },
    TermStructure { spread_pct: f64 },
    Skew { skew_pct: f64 },
}

impl std::fmt::Display for AlertType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AlertType::AbsoluteIv { .. } => write!(f, "absolute_iv"),
            AlertType::RateChange { .. } => write!(f, "rate_change"),
            AlertType::TermStructure { .. } => write!(f, "term_structure"),
            AlertType::Skew { .. } => write!(f, "skew"),
        }
    }
}

/// An alert generated by an AlertHandler
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    /// Alert type
    pub alert_type: AlertType,

    /// Tenor classification (short/medium/long)
    pub tenor: Tenor,

    /// Symbol that triggered the alert
    pub symbol: String,

    /// Current IV value
    pub iv: f64,

    /// Message to send to user
    pub message: String,

    /// Unix timestamp in milliseconds
    pub timestamp: u64,

    /// Data source name
    pub source: String,
}

impl Alert {
    pub fn new(
        alert_type: AlertType,
        tenor: Tenor,
        symbol: String,
        iv: f64,
        message: String,
        timestamp: u64,
        source: String,
    ) -> Self {
        Self {
            alert_type,
            tenor,
            symbol,
            iv,
            message,
            timestamp,
            source,
        }
    }
}
