apiVersion: v1
kind: ConfigMap
metadata:
  name: sandbox-ansible-prod
  namespace: vol-agent-system
  labels:
    app.kubernetes.io/name: sandbox-ansible-prod
    app.kubernetes.io/part-of: vol-agent
    app.kubernetes.io/component: runtime-config
data:
  ansible-prod.toml: 'name = "ansible-prod"

    provider = "ssh"

    work_dir = "/opt/ansible"

    host = "192.168.2.106"

    port = 22

    user = "root"

    key_path = "/app/.ssh/id_ed25519"

    host_key = "SHA256:8Y3g9hVzSz+KhN4oyodOoP4a+UOMUM0j3C9+CSDB1Ek="

    '
