apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-sandboxes
  namespace: vol-agent-system
  labels:
    app.kubernetes.io/name: agent-sandboxes
    app.kubernetes.io/part-of: vol-agent
    app.kubernetes.io/component: runtime-config
data:
  local-for-cli.toml: 'name = "local-for-cli"

    type = "local"

    work_dir = "/tmp"

    '
  ansible-prod.toml: 'name = "ansible-prod"

    type = "ssh"

    work_dir = "/opt/ansible"


    [ssh]

    host = "192.168.2.106"

    port = 22

    user = "root"

    identity_file = "/app/.ssh/id_ed25519"

    idle_timeout_secs = 300

    connect_timeout_secs = 10

    '
  ssh-dev.toml: 'name = "ssh-dev"

    type = "ssh"

    work_dir = "/tmp/sandbox-agent"


    [ssh]

    host = "192.168.2.106"

    port = 22

    user = "root"

    identity_file = "/app/.ssh/id_ed25519"

    known_hosts_file = "/app/.ssh/known_hosts"

    idle_timeout_secs = 300

    connect_timeout_secs = 10

    '
