apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-github-secret
  namespace: vol-agent-system
spec:
  encryptedData:
    GITHUB_TOKEN: AgCcRloYfhsO+J/8f8Dz8oZlRZ1MwY0+qNxhgNiC8Bn5SGzbEwV5EuLZXYEuXqaK+pAw5tSSbKJlLfsXFWA5bDKBU73ouD8xYmSGjEybPf0z2K4Td6IA2YjTRLt0vRDY1PBK05LjUhrz4sbv+gFxGDakm35PtVbfpXTvKpiEcf4h0hNNH9XUXMcWqx9RBvK2jqrIyrsiUaHKFAmklZs24CwTDy41CDSxN8h7My8iKhrWu7juwpz49zUDTVAn0oubqKZTCGvCdRaRsTamZfv6QsOT1G7nXFyV1TZLm0mRFi02JVb+TWrL7B9bkfV2kmwB35JqJcxF3LK5ZWwDRi0BOHHBZsJuZNyVP5LgcJsiB1+0RuEuDUqXOCw4w28lNRunLyMlnvrNlLid6zmpElkz+VD8VvgVI+PWudcm0JAlFhXE9lvzN7Ug5L+6ap4MOV6RzBOwZnvJFH9H718Y2tCocrd1edUhjndX+sfeirR/9za9IM1uezXQYzO52lAK1RR8dcibpW0yW7zOStSOisEg7+nwV0ju0FbHsWDbJr7QRhrTFSK7YA9kw1UdqpGHsLR1C80tc5s7NsqQWtnRusjYIppgday7JOnambXLLm91i++6jmOGGmLGLQGhoJZxWBs/AXblOCLWCC9J6pH+7eZQ/ZO3E4CB9XLSW85BwB9S2BsJePrmmFM/yKr1+rw2K/XvXgOK+JftOtpwRUVYY6LAGXurZXzBJ4qyb+F6Bb+Kh3dYTxS/X3jKxUPD
  template:
    metadata:
      name: agent-github-secret
      namespace: vol-agent-system
    type: Opaque

